apiVersion: apps/v1
kind: Deployment
metadata:
  name: branchreport-service
  namespace: demo
  labels:
    app: branchreport-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branchreport-service
  template:
    metadata:
      labels:
        app: branchreport-service
    spec:
      containers:
        - name: branchreport-service
          image: heangchihav/branchreport-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          envFrom:
            - secretRef:
                name: demo-secrets
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/branchreport_service_db
            - name: PORT
              value: "8085"
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: branchreport-service
  namespace: demo
spec:
  selector:
    app: branchreport-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: ClusterIP
