apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-service
  namespace: demo
  labels:
    app: marketing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketing-service
  template:
    metadata:
      labels:
        app: marketing-service
    spec:
      containers:
        - name: marketing-service
          image: heangchihav/marketing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          envFrom:
            - secretRef:
                name: demo-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SPRING_DATASOURCE_URL_MARKETING_SERVICE
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: USER_SERVICE_URL
              value: http://user-service:8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-service
  namespace: demo
spec:
  selector:
    app: marketing-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP
