apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: demo
data:
  create-databases.sql: |
    CREATE DATABASE user_service_db;
    CREATE DATABASE call_service_db;
    CREATE DATABASE marketing_service_db;
    CREATE DATABASE delivery_service_db;
    CREATE DATABASE branchreport_service_db;
