version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: demo-jenkins
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_certs:/certs/client
      - ../../:/workspace:ro
    networks:
      - jenkins-network
    depends_on:
      - docker

  docker:
    image: docker:24.0.6-dind
    container_name: jenkins-docker
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_certs:/certs/client
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins-network

volumes:
  jenkins_data:
    driver: local
  jenkins_certs:
    driver: local

networks:
  jenkins-network:
    driver: bridge
