apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
  namespace: demo
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
