apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: demo
data:
  # Spring Boot configuration
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_DATASOURCE_URL_USER_SERVICE: "jdbc:postgresql://postgres-service:5432/user_service_db"
  SPRING_DATASOURCE_URL_CALL_SERVICE: "jdbc:postgresql://postgres-service:5432/call_service_db"
  SPRING_DATASOURCE_URL_MARKETING_SERVICE: "jdbc:postgresql://postgres-service:5432/marketing_service_db"
  SPRING_DATASOURCE_URL_DELIVERY_SERVICE: "jdbc:postgresql://postgres-service:5432/delivery_service_db"
  SPRING_DATASOURCE_URL_BRANCHREPORT_SERVICE: "jdbc:postgresql://postgres-service:5432/branchreport_service_db"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Gateway CORS configuration
  GATEWAY_CORS_ALLOWED_ORIGIN_PATTERNS: "${GATEWAY_CORS_ALLOWED_ORIGIN_PATTERNS}"
  ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"
  COOKIE_SECURE: "${COOKIE_SECURE}"
