apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: demo
type: Opaque
data:
  # Tunnel credentials file - base64 encoded
  # To update: base64 -w 0 ../cloudflared/demo-tunnel.json
  demo-tunnel.json: eyJBY2NvdW50VGFnIjoiZjQ1NzA1MmIxYzhmNzZiYzNjODA4MGZkN2M0OGFhOWMiLCJUdW5uZWxTZWNyZXQiOiJEbjZabUh2VzN4L09INSszZGlmQ1Y4WlZUandYa2xQZXk4SnN1dmt5alV3PSIsIlR1bm5lbElEIjoiYjNlZGE3NTItNWRhZC00YmViLWE3MGYtNDRhNGRjZjJiOWJjIiwiR2xvYmFsIjpmYWxzZX0=
  
  # Origin certificate - base64 encoded
  # To update: base64 -w 0 ../cloudflared/cert.pem
  cert.pem: LS0tLS1CRUdJTiBBUkdPIFRVTk5FTCBUT0tFTi0tLS0tCmV5SjZiMjVsU1VRaU9pSXdZVEF3TkRZMFl6VXpOMkV4TmpKaFlUSTNaR0UzWVRCalpEUXpOekJoTVNJc0ltRmoKWTI5MWJuUkpSQ0k2SW1ZME5UY3dOVEppTVdNNFpqYzJZbU16WXpnd09EQm1aRGRqTkRoaFlUbGpJaXdpWVhCcApWRzlyWlc0aU9pSjFibkY0TUhwUVUwTk5helZvWlRkMlJtRnRka1F5ZUZCS1QwVkhWbll3U1ROcVZYTXlXSE4yCkluMD0KLS0tLS1FTkQgQVJHTyBUVU5ORUwgVE9LRU4tLS0tLQo=
